### PR TITLE
Fix compilation error on Ubuntu.

### PR DESCRIPTION
**Pull request by johnwbyrd**
LLVM itself does not refer to std::make_unique() as your code does.  Instead, it refers to llvm::make_unique(), which does the same thing.  This can be confirmed by grepping the rest of LLVM.

This change makes your codebase compile on Ubuntu 16.04 and probably other platforms as well.

### CODE REVIEW

**Comment by beholdnec** [comment]
Merged. Thanks!
